# Generated by Django 2.2.1 on 2019-06-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=128)),
                ('season', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('team1', models.CharField(max_length=128)),
                ('team2', models.CharField(max_length=128)),
                ('toss_winner', models.CharField(max_length=128)),
                ('toss_decision', models.CharField(max_length=128)),
                ('match_result', models.CharField(max_length=128)),
                ('dl_applied', models.BooleanField()),
                ('winner', models.CharField(max_length=128)),
                ('win_by_run', models.CharField(max_length=128)),
                ('win_by_wicket', models.CharField(max_length=128)),
                ('player_of_match', models.CharField(max_length=128)),
                ('venue', models.CharField(max_length=128)),
                ('umpire1', models.CharField(max_length=128)),
                ('umpire2', models.CharField(max_length=128)),
                ('umpire3', models.CharField(max_length=128)),
            ],
        ),
    ]
