# Generated by Django 2.2.1 on 2019-06-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_result',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_of_match',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='season',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='toss_decision',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='toss_winner',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='umpire1',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='umpire2',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='umpire3',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='win_by_run',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='win_by_wicket',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
