# Generated by Django 2.2.1 on 2019-06-17 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190617_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField()),
                ('innings', models.IntegerField()),
                ('batting_team', models.CharField(max_length=128)),
                ('bowling_team', models.CharField(max_length=128)),
                ('over', models.IntegerField()),
                ('ball', models.IntegerField()),
                ('batsman', models.CharField(max_length=128)),
                ('non_striker', models.CharField(max_length=128)),
                ('bowler', models.CharField(max_length=128)),
                ('is_super_over', models.IntegerField()),
                ('wide_run', models.IntegerField()),
                ('bye_run', models.IntegerField()),
                ('legbye_run', models.IntegerField()),
                ('noball_run', models.IntegerField()),
                ('penality_run', models.IntegerField()),
                ('batsman_run', models.IntegerField()),
                ('extra_run', models.IntegerField()),
                ('total_run', models.IntegerField()),
                ('player_dismissed', models.CharField(blank=True, max_length=128, null=True)),
                ('dismissal_kind', models.CharField(blank=True, max_length=128, null=True)),
                ('fielder', models.CharField(blank=True, max_length=128, null=True)),
                ('matchh_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Match')),
            ],
        ),
    ]
